
name: MuseGANPrototype
seed: 42
device: auto
g_temp_number: 5
bar_generator_number: 5

dataset:
  path: training_data/train_x_lpd_5_phr.npz
  batch_size: 128
  num_workers: 2
  shuffle: True
  drop_last: True
  expected_tracks: 5
  prefetch_factor: 2

# generator:
#   module: models.generator
#   model_class_name: BarGenerator
#   kwargs:
#     input_size: 128
#     out_channels: 5

# discriminator:
#   module: models.discriminator
#   model_class_name:  Discriminator
#   kwargs:
#     in_channels: 5
#     out_channels: 1

# optimizer:
#   generator:
#     learning_rate: 0.0002
#     beta1: 0.5
#     beta2: 0.999
#   discriminator:
#     learning_rate: 0.0002
#     beta1: 0.5
#     beta2: 0.999

# training:
#   max_steps: 1000
#   log_steps: 50
#   save_checkpoints_steps: 500
#   d_steps: 5
#   g_steps: 1
#   warmup_steps: 5

output:
  log_dir: logs_tensorboard/prototype 
  checkpoints_dir: checkpoints/prototype